# Generated by Django 6.0.6 on 2026-07-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contractor_verification_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='government_ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
