# Generated by Django 6.0.6 on 2026-07-03 08:42

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio_user_hourly_rate_user_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='government_id',
            field=models.FileField(blank=True, null=True, storage=accounts.storage.PrivateMediaStorage(), upload_to='government_ids/'),
        ),
    ]
